### ISSUE TITLE
Need Version 2.0.0 Back

### ISSUE THREAD

**Issue by emman-ok** [sevar83/android-spatialite#15]
Hello 

Please we can't seem to use version 2.0.0 as it is no longer available on jitpack repository.

`implementation 'com.github.sevar83:android-spatialite:2.0.0'`

```
ERROR: Failed to resolve: android-spatialite
Affected Modules: app
```

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find android-spatialite.jar (com.github.sevar83:android-spatialite:2.0.0).
     Searched in the following locations:
         https://jitpack.io/com/github/sevar83/android-spatialite/2.0.0/android-spatialite-2.0.0.jar
```

Further investigation shows that the version 2.0.0 is no longer available on Jitpack.io

I have tried to upgrade to version 2.0.1
But its throwing some Errors also.

```
021-05-02 06:55:33.549 1666-2271/com.asaasegps.fameko A/saasegps.famek: jni_internal.cc:814] JNI FatalError called: Native registration unable to find class 'org/spatialite/database/SQLiteConnection'; aborting...
/apex/com.android.runtime/lib/libopenjdkjvm.so (JVM_NativeLoad+248)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at java.lang.Runtime.nativeLoad(Native method)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at java.lang.Runtime.nativeLoad(Runtime.java:1115)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at java.lang.Runtime.loadLibrary0(Runtime.java:1069)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   - locked <0x02fa8002> (a java.lang.Runtime)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at java.lang.System.loadLibrary(System.java:1667)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at org.spatialite.database.SQLiteDatabase.<clinit>(SQLiteDatabase.java:81)
2021-05-02 06:55:33.989 1666-2271/com.asaasegps.fameko A/saasegps.famek: runtime.cc:630]   at org.spatialite.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:670)
```

Please can you host back the version 2.0.0

Thank you

**Comment by invweb** [comment]
+1
